######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 7 17:28:10 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += canvas.h mainWin.h searcher.h shape.h
SOURCES += canvas.cpp main.cpp mainWin.cpp searcher.cpp shape.cpp
