######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 9 17:30:14 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += canvas.h mainWin.h searcher.h shape.h
SOURCES += canvas.cpp main.cpp mainWin.cpp searcher.cpp shape.cpp
